name: Continuous integration

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]
    tags : [ 'v*' ]

env:
  SBT_TPOLECAT_CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache sbt
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*.scala') }}-${{ hashFiles('project/build.properties') }}

      - name: Check headers and formatting
        run: sbt headerCheck scalafmtCheckAll scalafmtSbtCheck 'scalafixAll --check'

      - name: Build & test
        run: sbt clean coverage test IntegrationTest/test coverageOff coverageReport

    services:
      mongo:
        image: mongo:4.4@sha256:e0dc28ed5e0d6340c6f3def017cf0ae6078dbd155f97f643105b11a24f54cadf
        ports:
          - 27017:27017
          - 27018:27018
          - 27019:27019
