name: Continuous integration

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]
    tags : [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache sbt
        uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
            ~/AppData/Local/Coursier/Cache/v1
            ~/Library/Caches/Coursier/v1
          key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/*.scala') }}-${{ hashFiles('project/build.properties') }}

      - name: Check headers and formatting
        run: sbt headerCheck scalafmtCheckAll scalafmtSbtCheck 'scalafixAll --check'

      - name: Build & test
        run: sbt clean coverage test IntegrationTest/test coverageOff coverageReport

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
          - 27018:27018
          - 27019:27019
