name: Release

on: 
  workflow_run:
    workflows: ["Continuous integration"]
    branches: [main]
    types: [completed]

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          release_name: "<RELEASE_VERSION>"
          tag_prefix: "v"
          bump_version_scheme: minor
          use_github_release_notes: true
